[project]
authors = [
  "Brian H. Toby <toby@anl.gov>",
  "Robert B. Von Dreele <vondreele@anl.gov>",
  ]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi"
platforms = ["linux-64", "win-64", "osx-arm64"]


[pypi-dependencies]


[tasks]

clean-build = { cmd = "(rm dist/*whl || true) && (rm -r build || true) ", cwd='../' }

build =  { cmd = "python -m build -wnx -vvvv -Cbuild-dir='build'", cwd='../', depends_on = ['clean-build']}
install = { cmd = "pip install dist/*whl --force-reinstall --no-deps" , cwd='../', depends_on=['build']}
install-editable =  { cmd = "pip install -ve . --no-build-isolation" , cwd='../', depends_on=['clean-build']}

build-win =  { cmd = "python -m build -wnx -vvvv -Cbuild-dir='build'", cwd='../', depends_on = ['clean-build'], env={CC = 'clang-cl', CXX ='clang-cl'}}
install-win = { cmd = "pip install dist/*whl --force-reinstall --no-deps" , cwd='../', depends_on=['build-win']}
install-editable-win =  { cmd = "pip install -ve . --no-build-isolation" , cwd='../', depends_on=['clean-build'] , env={CC = 'clang-cl', CXX ='clang-cl'}}

build-and-go ={ depends_on= ["install", "ui"]}
build-and-go-win ={ depends_on= ["install-win", "ui"]}

test = {cmd = "python -m pytest ../" }

ui = "python -m GSASII"


[dependencies]
cython = ">=3.0.11,<4"
h5py = ">=3.12.1,<4"
imageio = ">=2.36.1,<3"
matplotlib = ">=3.10.0,<4"
meson-python = ">=0.17.1,<0.18"
ninja = ">=1.12.1,<2"
numpy = ">=2.2.1,<3"
pillow = ">=11.1.0,<12"
pkg-config = ">=0.29.2,<0.30"
pyopengl = ">=3.1.6,<4"
pyproject-metadata = ">=0.9.0,<0.10"
requests = ">=2.32.3,<3"
scipy = ">=1.15.0,<2"
tomli = ">=2.2.1,<3"
wheel = ">=0.45.1,<0.46"
wxpython = ">=4.2.2,<5"
pip = ">=24.3.1,<25"
python-build = ">=1.2.2.post1,<2"
zarr = "*"
xmltodict = ">=0.14.2,<0.15"
compilers = ">=1.8.0,<2"
clang = ">=17.0.6,<20"
pycifrw = ">=4.4.0"
pytest = ">=8.3.4,<9"

[feature.py311.dependencies]
python = "<3.12,>=3.11"

[feature.py312.dependencies]
python = "<3.13,>=3.12"

[feature.py313.dependencies]
python = "<3.14,>=3.13"

[feature.py310.dependencies]
python = "<3.11,>=3.10"

[environments]
py310 = ['py310']
py311 = ['py311']
py312 = ['py312']
py313 = ['py313']
