[project]
authors = [
  "Brian H. Toby <toby@anl.gov>",
  "Robert B. Von Dreele <vondreele@anl.gov>",
  ]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi"
platforms = ["linux-64", "win-64"]


[pypi-dependencies]


[tasks]
ui= "python -m GSASII.GSASII"
build =  { cmd = "(rm dist/*whl || true) && python -m build -wnx && pip install dist/*whl --force-reinstall --no-deps", cwd='../'}

[dependencies]
compilers = ">=1.7.0,<2"
cython = ">=3.0.11,<4"
h5py = ">=3.12.1,<4"
imageio = ">=2.36.1,<3"
matplotlib = ">=3.10.0,<4"
meson-python = ">=0.17.1,<0.18"
ninja = ">=1.12.1,<2"
numpy = ">=2.2.1,<3"
pillow = ">=11.0.0,<12"
pkg-config = ">=0.29.2,<0.30"
pybind11 = ">=2.13.6,<3"
pyopengl = ">=3.1.6,<4"
pyproject-metadata = ">=0.9.0,<0.10"
requests = ">=2.32.3,<3"
scipy = ">=1.14.1,<2"
setuptools = ">=75.6.0,<76"
setuptools_scm = ">=8.1.0,<9"
tomli = ">=2.2.1,<3"
wheel = ">=0.45.1,<0.46"
wxpython = ">=4.2.2,<5"
pip = ">=24.3.1,<25"
python-build = "*"
zarr = ">=2.18.4,<3"
xmltodict = ">=0.14.2,<0.15"
