channels:
  - conda-forge
dependencies:
  - python
  - conda
  - scipy
  - pyopengl
  - imageio
  - h5py
  - numpy
#  - sphinx # included by RTD
#  - pillow # included by RTD
  - pip
  - matplotlib
#  - wxpython # slows down conda too much?
