name: install self-installer on Windows

on:
  workflow_dispatch:    # Allows running this workflow manually
  # Runs on pushes targeting the default branch
  push:
    branches-ignore:
      - master
  #   branches: ['main']
#  pull_request:
#    branches: ['main']


jobs:
  test-GSAS-II:
    #strategy:
    #  fail-fast: false
    runs-on: 'windows-latest'
    steps:
      - uses: suisei-cn/actions-download-file@818d6b7dc8fe73f2f924b6241f2b1134ca1377d9 # 1.6.0
        id: downloadfile
        name: Download the file
        with:
          url: "https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/releases/download/v1.0.1/gsas2full-Latest-Windows-x86_64.exe"
          target: download/

      - name: GSAS-II single test
        shell: pwsh
        run: Start-Process -FilePath .\download\gsas2new-5804-Windows-x86_64.exe -ArgumentList "/S /AddToPath=1 /D=.\G2 " -NoNewWindow -Wait

      - name: GSAS-II all tests
        if: always()
        shell: bash -el {0}
        run: |
          cd G2
          ls

      - name: try pyspg
        if: always()
        shell: bash -el {0}
        run: |
          cd G2
          Scripts\activate
          where python
          python -VV
          conda install pytest -y
          python -m pytest



      #     #python -v -c "import sys; print(sys.path)"
      #     python -c "import pyspg"

      # - name: try ldd
      #   if: always()
      #   shell: bash -el {0}
      #   run: |
      #     #conda create -n ntldd python=3.12 numpy=2.2 m2w64-ntldd-git
      #     conda create -n ntldd python=3.11 numpy=1.26 m2w64-ntldd-git
      #     conda activate ntldd
      #     cd GSAS-II/GSASII-bin/win_64_p3.11_n1.26
      #     #cd GSAS-II/GSASII-bin/win_64_p3.12_n2.2
      #     ls
      #     ntldd *.pyd
      #     python -c "import pyspg"
